### ISSUE TITLE
win 7 and resolution

### ISSUE THREAD

**Issue by johnbun04** [JacksonElia/AFK_Apex_Bot#4]
hii
 
is the program intended to work on windows 7? i tried but it gives error api-ms-win-core-path-l1-1-0.dll and then another one saying py39 dll module not found.

and if i upgrade on win 10, will it work on 1600x900 res?

thank you

**Comment by Traptricker** [comment]
It only works on windows 10. And no, resolution has to be 1080p or 1440p, sorry.
