### ISSUE TITLE
Not really an issue, more like a suggestion

### ISSUE THREAD

**Issue by Brxby** [JacksonElia/AFK_Apex_Bot#7]
Dying by falling from the map also counts as a death so you can do it faster by just making the character turn 180 and straight into the ocean. This way you get 5-7x more deaths an hour. I cant do this change myself cuz im not good with coding but it would be great if you could at least make it an option.

**Comment by Brxby** [comment]
i was trying to do it myself but i got an error that "name 'launch_bot' is not defined" and i couldnt go any further from there cuz idk how to fix that.

**Comment by Brxby** [comment]
okay after long stupid thinking i figured out that something MUST be missing here.

![image_2022-12-12_191949891](https://user-images.githubusercontent.com/120403978/207111154-70fd24bd-9945-4314-9988-8aaa18c8ab70.png)
![image_2022-12-12_192011405](https://user-images.githubusercontent.com/120403978/207111244-8ca01ded-d374-4685-a87a-2c2464f69b90.png)
you dont mention this launch bot anywhere else in all of the files

**Comment by JacksonElia** [comment]
Thanks for the suggestion!

I’ll look into it, but before, when I checked if falling off the map counted as a death, it did not affect your player stats.

Also, you must have accidentally deleted some code, launch_bot is right under the area of code you were talking about.

**Comment by JacksonElia** [comment]
![image](https://user-images.githubusercontent.com/85963782/207135934-5a302e16-0963-41bb-be4a-fd4e650e0d10.png)

**Comment by Brxby** [comment]
hmm thats strange, for me it counts the deaths and the kdr goes down. Also thanks for telling me about the missing lines i will try to change your code to do what i want to if you dont wanna bother, its fun anyways.

**Comment by JacksonElia** [comment]
That would be great! If you want to submit a pull request, please do so.
