### ISSUE TITLE
Fill Teammate Bug and HDR

### ISSUE THREAD

**Issue by Hong-Bug** [JacksonElia/AFK_Apex_Bot#9]
if you start the bot while the fill teammate is already off it will stuck
Turning on HDR might let the bot stuck because in the view of the bot it look brighter
![Screenshot 2022-12-20 184144](https://user-images.githubusercontent.com/120415162/208647965-72ce88eb-fba3-4475-8d5a-8bd648de4113.png)

**Comment by JacksonElia** [comment]
Did you download the newest update I released like a week ago?

**Comment by Hong-Bug** [comment]
> Did you download the newest update I released like a week ago?
> […](#)
> On Dec 20, 2022, at 5:42 AM, Hong-Bug ***@***.***> wrote: ﻿ if you start the bot while the fill teammate is already off it will stuck Turning on HDR might let the bot stuck because in the view of the bot it look brighter — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

yes I did this happen afther this update

**Comment by JacksonElia** [comment]
Yes HDR might be the issue then, I made this without it.

**Comment by Hong-Bug** [comment]
> Yes HDR might be the issue then, I made this without it.
> […](#)
> On Dec 20, 2022, at 10:04 PM, Hong-Bug ***@***.***> wrote: ﻿ Did you download the newest update I released like a week ago? … On Dec 20, 2022, at 5:42 AM, Hong-Bug @.***> wrote: ﻿ if you start the bot while the fill teammate is already off it will stuck Turning on HDR might let the bot stuck because in the view of the bot it look brighter — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. yes I did this happen afther this update — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
